export const UPDATE_CURRENT_STAIRWELL = 'UPDATE_CURRENT_STAIRWELL';
export const GET_STAIRWELL = 'GET_STAIRWELL';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const GET_PROJECT = 'GET_PROJECT';
export const GET_PROJECT_GUID = 'GET_PROJECT_GUID';
export const GET_FLOOR_LEVELS = 'GET_FLOOR_LEVELS';
export const GET_FLOOR_PLANS = 'GET_FLOOR_PLANS';
export const TOGGLE_STAIR_REFLOW_FLAG = 'TOGGLE_STAIR_REFLOW_FLAG';