const configuratorSample = {
    "id": 6,
    "assemblyId": 0,
    "stairName": "Stair 2 Upper B",
    "isClockwise": false,
    "project": null,
    "currentStep": 0,
    "treadWidth": 0,
    "stairWidth": "53.75",
    "stairLength": 252,
    "stairwellWidth": 114,
    "stairwellWidthF": null,
    "predeterminedStairwellLength": null,
    "minimumRiserHeight": null,
    "railingType": null,
    "exteriorRailType": null,
    "interiorRailType": null,
    "stairwellLengthHandling": null,
    "stairwellWidthHandling": null,
    "stairwellExcessLengthHandling": null,
    "landingsAtFloorLevels": null,
    "floorLevelLandingSupportType": null,
    "intermediateLandingSupportType": null,
    "landingElevationDelta": null,
    "minimumLandingWidth": 0,
    "stairEdgeOffset": 1,
    "maxFlightRise": null,
    "bottomLevelId": 0,
    "topLevelId": 0,
    "landingsLevels": null,
    "defaultStoryHeight": null,
    "stories": null,
    "floorLevels": null,
    "planLevels": null,
    "planLevel": null,
    "flights": [
        {
            "flightId": 0,
            "story": 0,
            "name": "Level 2A",
            "topElevation": 1452,
            "bottomElevation": 1392,
            "isClockwise": false,
            "risers": 9,
            "riserHeight": 6.666666666666667,
            "riseHeight": 60,
            "runLength": 88,
            "isBottomStair": false,
            "isDdl": false,
            "isTopStair": false,
            "isDogLeg": false,
            "dogLegLength": 0,
            "stringerThickness": 0.25,
            "landingWidth": 103.875,
            "landingLength": 114,
            "stairEdgeOffset": 1,
            "hasLanding": false,
            "landingSupportType": null,
            "landingElevationDelta": 0,
            "landingHasRightStandPipePenetration": false,
            "landingHasLeftStandPipePenetration": false,
            "stairWidth": 53.75,
            "exteriorRailType": "handrail",
            "interiorRailType": "guardrail",
            "railingPanelType": 0,
            "isBridge": false,
            "hasLandingRail": false
        }
    ],
    "location": null,
    "boundingBox": null
}
export const baseKeys = Object.keys(configuratorSample);
export const flightKeys = Object.keys(configuratorSample.flights[0])